repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black" ]
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      -   id: flake8
          additional_dependencies: ["flake8-bugbear==19.3.0"]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.2.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-o", "requirements.txt", "--without-hashes"]

